T5971: Added PPP options documentation
vyos/vyos-documentation pull request #1263
Opened 2024-02-02 16:13 UTC by aapostoliuk

Added PPP options documentation

2024-02-02 19:43 UTC, rebortg requested changes

2024-02-02 19:43 UTC, rebortg commented on docs/configuration/vpn/sstp.rst
> +  value `<number>`, the session will be reset.Default value is **3**.
missing space

2024-02-05 08:42 UTC, aapostoliuk commented on docs/configuration/vpn/sstp.rst
> +  value `<number>`, the session will be reset.Default value is **3**.
done

2024-02-08 08:59 UTC, merged

2024-02-08 09:02 UTC, rebortg commented
@mergifyio backport sagitta