Rewritten the SSTP server documentation
vyos/vyos-documentation pull request #1300
Opened 2024-02-29 14:25 UTC by aapostoliuk

Fully rewritten SSTP server documentation.

2024-03-04 19:40 UTC, rebortg requested changes

2024-03-04 19:40 UTC, rebortg commented on docs/configuration/vpn/sstp.rst
> +RADIUS server is used. With VyOS 1.2 you can bind all outgoing RADIUS requests
VyOS 1.2
same as pptp PR

2024-03-05 08:33 UTC, aapostoliuk commented on docs/configuration/vpn/sstp.rst
> +RADIUS server is used. With VyOS 1.2 you can bind all outgoing RADIUS requests
done

2024-03-05 20:26 UTC, rebortg commented
@Mergifyio backport sagitta

2024-03-05 20:26 UTC, merged