Rewritten the PPTP server documentation
vyos/vyos-documentation pull request #1301
Opened 2024-02-29 15:54 UTC by aapostoliuk

Fully rewritten PPTP server documentation.

2024-03-04 19:36 UTC, rebortg requested changes

2024-03-04 19:36 UTC, rebortg commented on docs/configuration/vpn/pptp.rst
> +RADIUS server is used. With VyOS 1.2 you can bind all outgoing RADIUS requests
VyOS 1.2 ?
either delete or "since VyOS 1.2"?

2024-03-04 19:40 UTC, rebortg requested changes

2024-03-04 19:40 UTC, rebortg commented on docs/configuration/vpn/pptp.rst
> +    Feb 29 14:58:57 vyos accel-pptp[4629]: pptp: new connection from 192.168.10.100
a command is missing

2024-03-05 08:25 UTC, aapostoliuk commented on docs/configuration/vpn/pptp.rst
> +    Feb 29 14:58:57 vyos accel-pptp[4629]: pptp: new connection from 192.168.10.100
done

2024-03-05 08:26 UTC, aapostoliuk commented on docs/configuration/vpn/pptp.rst
> +RADIUS server is used. With VyOS 1.2 you can bind all outgoing RADIUS requests
done. I have deleted '1.2'

2024-03-05 20:26 UTC, merged