Update and add information about Terraform
vyos/vyos-documentation pull request #1305
Opened 2024-03-05 05:34 UTC by mkorobeinikov

- update AWS + terraform
index
- add Azure + terraform
vSpgere + terraform

2024-03-06 21:14 UTC, rebortg requested changes
there are some typos and other small stuff. Please try to wrote brand names correctly.

The Steps are look strange in the renderd [page](https://vyos--1305.org.readthedocs.build/en/1305/automation/terraform/terraformvSphere.html). i would prefer to use the sphinx syntax for enumeration and prevent of using "1.1" or "2.2". just use the single number an 2 space indentation. Maybe have the lowest header level on each step section will also help for a better look.

2024-03-06 21:14 UTC, rebortg commented on docs/automation/terraform/terraformvSphere.rst
> +Deploying vyos in the vSphere infrastructia
typo: infrastructia

2024-03-06 21:14 UTC, rebortg commented on docs/automation/terraform/terraformAZ.rst
> +Deploying vyos in the Azure cloud
VyOS

2024-03-06 21:14 UTC, rebortg commented on docs/automation/terraform/terraformAZ.rst
> +With the help of terraforms, you can quickly deploy Vyos-based infrastructure in the Azure cloud. If necessary, the infrastructure can be removed using terraform.
missing blank line between headline an next text

2024-03-07 02:27 UTC, mkorobeinikov commented on docs/automation/terraform/terraformvyos.rst
> +  #terraform plan          # show wtah is changing
done

2024-03-07 02:27 UTC, mkorobeinikov commented on docs/automation/terraform/terraformvyos.rst
> +More detailed about what is Terraform you can write using the link_.
done

2024-03-10 20:02 UTC, merged

2024-03-11 14:14 UTC, rebortg commented
@mergifyio backport sagitta