Update article about terraform in saggita
vyos/vyos-documentation pull request #1323
Opened 2024-03-13 04:15 UTC by mkorobeinikov

Update article about terraform like 1.5

2024-03-13 21:34 UTC, rebortg commented
there are some build warning, regarding to the PR
```
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/index.rst:5: WARNING: toctree contains reference to nonexisting document 'automation/vyos-pyvyos'
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:33: ERROR: Error in "image" directive:
no content permitted.
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/sg.png
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/traffic.png
```

2024-03-13 21:35 UTC, rebortg requested changes
there are some build warning, regarding to the PR
```
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/index.rst:5: WARNING: toctree contains reference to nonexisting document 'automation/vyos-pyvyos'
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:33: ERROR: Error in "image" directive:
no content permitted.
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/sg.png
/home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/traffic.png
```

2024-03-14 07:22 UTC, mkorobeinikov commented
> there are some build warning, regarding to the PR
> 
> ```
> /home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/index.rst:5: WARNING: toctree contains reference to nonexisting document 'automation/vyos-pyvyos'
> /home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:33: ERROR: Error in "image" directive:
> no content permitted.
> /home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/sg.png
> /home/docs/checkouts/readthedocs.org/user_builds/vyos/checkouts/1323/docs/automation/terraform/terraformAWS.rst:: WARNING: image file not readable: _static/images/traffic.png
> ```

Done

2024-03-15 10:59 UTC, dmbaturin approved these changes

2024-03-16 11:32 UTC, merged