router-advert: T6681: add new option "no-send-interval"
vyos/vyos-documentation pull request #1534
Opened 2024-08-31 19:24 UTC by c-po

## Change Summary

## Related Task(s)

* https://vyos.dev/Txxxx

## Related PR(s)

* https://github.com/vyos/vyos-1x/pull/4022

## Backport

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-documentation/blob/current/CONTRIBUTING.md) document

2024-08-31 20:40 UTC, rebortg commented
@mergifyio backport sagitta

2024-08-31 20:40 UTC, rebortg approved these changes

2024-09-02 10:46 UTC, dmbaturin requested changes

2024-09-02 10:46 UTC, dmbaturin commented on docs/configuration/service/router-advert.rst
> +   If set, the router will no longer sends periodic router advertisements and not
```suggestion
   If set, the router will no longer send periodic router advertisements and will not
```

2024-09-02 10:46 UTC, dmbaturin commented on docs/configuration/service/router-advert.rst
> +   responds to router solicitations.
```suggestion
   respond to router solicitations.
```

Verb tense typos.

2024-09-03 08:29 UTC, merged

2024-09-03 08:54 UTC, dmbaturin commented
@mergifyio backport circinus