Update doc config vrf
vyos/vyos-documentation pull request #1538
Opened 2024-09-05 12:49 UTC by systeembeheerder

## Change Summary
Remove example without id. VyOS does not accept this example.
See https://forum.vyos.io/t/vrf-table-id-is-mandatory/13685

## Backport

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-documentation/blob/current/CONTRIBUTING.md) document

2024-09-05 14:40 UTC, dmbaturin requested changes

2024-09-05 14:40 UTC, dmbaturin commented on docs/configuration/vrf/index.rst
> +   Create new VRF instance with `<name>` and <id>. The name is used when placing
```suggestion
   Create a new VRF instance with `<name>` and <id>. The name is used when placing
```

2024-09-06 19:35 UTC, merged

2024-09-06 19:35 UTC, rebortg commented
@mergifyio backport sagitta

2024-09-06 19:36 UTC, rebortg commented
@mergifyio backport current