dhcp-server: ddns: T6773: DDNS configuration documentation
vyos/vyos-documentation pull request #1561
Opened 2024-10-12 03:14 UTC by abukharov

## Change Summary

Documentation for RFC-2136 DDNS updates in Kea DHCP4 server.

## Related Task(s)

https://vyos.dev/T6773

## Related PR(s)

## Backport

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-documentation/blob/current/CONTRIBUTING.md) document

2024-10-15 04:59 UTC, rebortg requested changes

2024-10-15 04:59 UTC, rebortg commented on docs/configuration/service/dhcp-server.rst
> +-----------------
```suggestion
-----------------------------
```

lines must have same size as headline text

2024-11-26 17:39 UTC, rebortg approved these changes
wait for feature merge

2024-11-26 22:05 UTC, abukharov commented
Changes to reflect some simplifications to the configuration language

2024-11-30 03:50 UTC, abukharov commented
Some more changes to the config language

2025-01-23 11:27 UTC, rebortg approved these changes

2025-04-26 09:29 UTC, abukharov commented
Hi @rebortg, the main PR has been now merged and I've update the doco to include all the final changes. I think this can be now safely merged.

2025-04-29 12:13 UTC, merged