updated wireguard docs for crux branch
vyos/vyos-documentation pull request #574
Opened 2021-07-19 18:47 UTC by usman-umer

Same changes made in my previous PR in the master branch, but for the crux branch instead.

2021-07-19 20:20 UTC, rebortg requested changes
i added some hints, crux have in some configs a different syntax.

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +.. opcmd:: show wireguard keypairs pubkey default
the command in crux is `show wireguard pubkey`

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +     vyos@vyos:~$ show wireguard keypairs pubkey default
`show wireguard pubkey`

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +.. opcmd:: generate wireguard named-keypairs <name>
`named-keypairs` are not available in crux

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> -  set interfaces wireguard wg01 peer to-wg02 endpoint '192.168.0.142:12345'
this is the correct syntax for the endpoint configuration in crux
`address` and `port` are not available in crux

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +.. cfgcmd:: set interfaces wireguard <interface> private-key <name>
this option is not available in crux

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +.. opcmd:: generate wireguard client-config <name> interface <interface> server <ip|fqdn> address <client-ip>
this is also not available in crux

2021-07-19 20:20 UTC, rebortg commented on docs/configuration/interfaces/wireguard.rst
> +.. opcmd:: show interfaces wireguard wg0 summary
command not available in crux

2021-07-20 10:07 UTC, usman-umer commented
Modified commands for crux.

2021-07-21 18:50 UTC, rebortg commented
sorry, there are still the wrong command in multiple locations.

this, for example, is wrong in crux:
`set interfaces wireguard wg01 peer to-wg02 address '<Site2 Pub IP>' `
`set interfaces wireguard wg01 peer to-wg02 port '58120'`

replace it with something like this:
`set interfaces wireguard wg01 peer to-wg02 endpoint '192.168.0.142:12345'`

2021-07-24 19:39 UTC, usman-umer commented
Replaced interface address with endpoint & ports.

2021-07-25 19:26 UTC, merged